export interface Entity {
    id: number,
    name?: string,
    costTitan?: number,
    costSilicon?: number,
    costPVC?: number,
    costTricium?: number,
    structure?: number,
    shield?: number,
    weapon?: number,
    regeneration?: number,
    experience?: boolean,
    wfFactor?: number,
    repairFactor?: number,
}